---
development:
  cloud_name: [cloud_name]
  api_key: "[api_key]"
  api_secret: [api_secret]
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: [cloud_name]
  api_key: "[api_key]"
  api_secret: [api_secret]
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: [cloud_name]
  api_key: "[api_key]"
  api_secret: [api_secret]
  enhance_image_tag: true
  static_file_support: false
